# Exemplo de configuração de secrets
# NUNCA commitar este arquivo!
# Copie para .streamlit/secrets.toml e configure seus valores

# ============================================
# SUPABASE
# ============================================
[supabase]  
url = "https://seu-projeto.supabase.co"
key = "sua-anon-key-aqui"
service_key = "sua-service-key-aqui"
connection_string = "postgresql://user:password@host:port/database"

# ============================================
# GOOGLE AI
# ============================================
[google_ai]
api_key = "sua-google-ai-key-aqui"

# ============================================
# GOOGLE OIDC (Autenticação)
# ============================================
[auth]
google_client_id = "seu-client-id.apps.googleusercontent.com"
google_client_secret = "GOCSPX-seu-secret"
google_redirect_uri = "http://localhost:8501"
secret = "sua-chave-secreta-aleatoria-muito-longa-e-segura-aqui"

# ============================================
# CONFIGURAÇÕES ADICIONAIS (Opcionais)
# ============================================

# Configurações de API (outras APIs)
[api]
openai_key = "sk-..."
anthropic_key = "sk-ant-..."

# Configurações de Banco de Dados (alternativo)
[database]
url = "postgresql://user:password@host:port/database"
username = "db_user"
password = "db_password"
host = "localhost"
port = 5432

# Configurações de Serviços
[services]
redis_url = "redis://localhost:6379"
elasticsearch_url = "http://localhost:9200"

# Configurações de Email
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
username = "seu_email@gmail.com"
password = "sua_senha_app"

# Configurações de Armazenamento
[storage]
aws_access_key = "AKIA..."
aws_secret_key = "wJalrXUtn..."
s3_bucket = "meu-bucket"
s3_region = "us-east-1"

# Configurações de Monitoramento
[monitoring]
sentry_dsn = "https://..."
datadog_api_key = "dd_api_key"
newrelic_license_key = "nr_license_key"
